add m4 config support for debian distros

diff --git a/packaging/debian/opensips.init b/packaging/debian/opensips.init
--- a/packaging/debian/opensips.init
+++ b/packaging/debian/opensips.init
@@ -19,6 +19,9 @@ PATH=/sbin:/bin:/usr/sbin:/usr/bin
 DAEMON=/usr/sbin/opensips
 NAME=opensips
 DESC=opensips
+CFGFILE=/etc/opensips/opensips.cfg
+M4CFGFILE=/etc/opensips/opensips.m4
+M4ARCHIVEDIR=/etc/opensips/archive
 HOMEDIR=/var/run/opensips
 PIDFILE=$HOMEDIR/$NAME.pid
 DEFAULTS=/etc/default/opensips
@@ -28,7 +31,7 @@ RUN_OPENSIPS=no
 # otherwise the boot process will just stop
 check_fork ()
 {
-    if grep -q "^[[:space:]]*fork[[:space:]]*=[[:space:]]*no.*" /etc/opensips/opensips.cfg; then
+    if grep -q "^[[:space:]]*fork[[:space:]]*=[[:space:]]*no.*" $CFGFILE; then
 	echo "Not starting $DESC: fork=no specified in config file; run /etc/init.d/opensips debug instead"
 	exit 1
     fi
@@ -118,6 +121,28 @@ case "$1" in
 	mkdir -p "$HOMEDIR"
 	chmod 775 "$HOMEDIR"
 	chown "$USER:$GROUP" "$HOMEDIR" >/dev/null 2>&1 || true
+
+	# Generate config from M4
+	if [ -f $M4CFGFILE ]; then
+		m4 -Q $M4CFGFILE >$CFGFILE.tmp
+		if [ $? != 0 ]; then
+			echo "Cannot process m4 macro"
+			rm "$CFGFILE.tmp"
+			exit 1
+		fi
+
+		[ -e $CFGFILE ] || touch $CFGFILE
+
+		# compare configs
+		if [ `md5sum $CFGFILE|awk '{print $1}'` != `md5sum $CFGFILE.tmp|awk '{print $1}'` ]; then
+			mkdir -p "$M4ARCHIVEDIR"
+			mv "$CFGFILE" "$M4ARCHIVEDIR/$NAME.cfg-`date +%Y%m%d_%H%M%S`"
+		fi
+
+		mv "$CFGFILE.tmp" "$CFGFILE"
+		chown $USER:$GROUP $CFGFILE
+		chmod 640 $CFGFILE
+	fi
 
 	echo -n "Starting $DESC: $NAME"
 	start-stop-daemon --start --quiet --pidfile $PIDFILE \
